language: node_js
node_js:
  - 13
services:
  - Docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "hellooooooooo"
script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml push